// Icons an admin can pick for cards and list items. Stored by name.
import {
  AlertTriangle,
  Award,
  BookOpen,
  Briefcase,
  Building,
  Calendar,
  Clock,
  DollarSign,
  Droplets,
  FileText,
  Globe,
  GraduationCap,
  HandHeart,
  Handshake,
  Heart,
  Home,
  Leaf,
  type LucideIcon,
  Mail,
  MapPin,
  Megaphone,
  Package,
  Phone,
  Scale,
  Shield,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Target,
  TreePine,
  TrendingUp,
  Users,
  Utensils,
  Zap,
} from "lucide-react"

export const ICONS: Record<string, LucideIcon> = {
  heart: Heart,
  users: Users,
  leaf: Leaf,
  "graduation-cap": GraduationCap,
  "map-pin": MapPin,
  home: Home,
  shield: Shield,
  zap: Zap,
  globe: Globe,
  megaphone: Megaphone,
  utensils: Utensils,
  "book-open": BookOpen,
  package: Package,
  handshake: Handshake,
  "dollar-sign": DollarSign,
  clock: Clock,
  phone: Phone,
  mail: Mail,
  droplets: Droplets,
  "hand-heart": HandHeart,
  stethoscope: Stethoscope,
  sprout: Sprout,
  "tree-pine": TreePine,
  target: Target,
  award: Award,
  star: Star,
  sun: Sun,
  building: Building,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  "file-text": FileText,
  calendar: Calendar,
  scale: Scale,
  "alert-triangle": AlertTriangle,
}

export const ICON_NAMES = Object.keys(ICONS)

export function getIcon(name: string | undefined): LucideIcon {
  return (name && ICONS[name]) || Heart
}
